#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TussentijdsProjectYannickOverzicht
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Projectweek Yannick")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdminRechten(AdminRechten instance);
    partial void UpdateAdminRechten(AdminRechten instance);
    partial void DeleteAdminRechten(AdminRechten instance);
    partial void InsertBestelling(Bestelling instance);
    partial void UpdateBestelling(Bestelling instance);
    partial void DeleteBestelling(Bestelling instance);
    partial void InsertBestellingProduct(BestellingProduct instance);
    partial void UpdateBestellingProduct(BestellingProduct instance);
    partial void DeleteBestellingProduct(BestellingProduct instance);
    partial void InsertCategorie(Categorie instance);
    partial void UpdateCategorie(Categorie instance);
    partial void DeleteCategorie(Categorie instance);
    partial void InsertKlant(Klant instance);
    partial void UpdateKlant(Klant instance);
    partial void DeleteKlant(Klant instance);
    partial void InsertLeverancier(Leverancier instance);
    partial void UpdateLeverancier(Leverancier instance);
    partial void DeleteLeverancier(Leverancier instance);
    partial void InsertPersoneelslid(Personeelslid instance);
    partial void UpdatePersoneelslid(Personeelslid instance);
    partial void DeletePersoneelslid(Personeelslid instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::TussentijdsProjectYannickOverzicht.Properties.Settings.Default.Projectweek_YannickConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AdminRechten> AdminRechtens
		{
			get
			{
				return this.GetTable<AdminRechten>();
			}
		}
		
		public System.Data.Linq.Table<Bestelling> Bestellings
		{
			get
			{
				return this.GetTable<Bestelling>();
			}
		}
		
		public System.Data.Linq.Table<BestellingProduct> BestellingProducts
		{
			get
			{
				return this.GetTable<BestellingProduct>();
			}
		}
		
		public System.Data.Linq.Table<Categorie> Categories
		{
			get
			{
				return this.GetTable<Categorie>();
			}
		}
		
		public System.Data.Linq.Table<Klant> Klants
		{
			get
			{
				return this.GetTable<Klant>();
			}
		}
		
		public System.Data.Linq.Table<Leverancier> Leveranciers
		{
			get
			{
				return this.GetTable<Leverancier>();
			}
		}
		
		public System.Data.Linq.Table<Personeelslid> Personeelslids
		{
			get
			{
				return this.GetTable<Personeelslid>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdminRechten")]
	public partial class AdminRechten : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AdminRechtenID;
		
		private string _titel;
		
		private EntitySet<Personeelslid> _Personeelslids;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdminRechtenIDChanging(int value);
    partial void OnAdminRechtenIDChanged();
    partial void OntitelChanging(string value);
    partial void OntitelChanged();
    #endregion
		
		public AdminRechten()
		{
			this._Personeelslids = new EntitySet<Personeelslid>(new Action<Personeelslid>(this.attach_Personeelslids), new Action<Personeelslid>(this.detach_Personeelslids));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminRechtenID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AdminRechtenID
		{
			get
			{
				return this._AdminRechtenID;
			}
			set
			{
				if ((this._AdminRechtenID != value))
				{
					this.OnAdminRechtenIDChanging(value);
					this.SendPropertyChanging();
					this._AdminRechtenID = value;
					this.SendPropertyChanged("AdminRechtenID");
					this.OnAdminRechtenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titel", DbType="NVarChar(20)")]
		public string titel
		{
			get
			{
				return this._titel;
			}
			set
			{
				if ((this._titel != value))
				{
					this.OntitelChanging(value);
					this.SendPropertyChanging();
					this._titel = value;
					this.SendPropertyChanged("titel");
					this.OntitelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AdminRechten_Personeelslid", Storage="_Personeelslids", ThisKey="AdminRechtenID", OtherKey="AdminRechtenID")]
		public EntitySet<Personeelslid> Personeelslids
		{
			get
			{
				return this._Personeelslids;
			}
			set
			{
				this._Personeelslids.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Personeelslids(Personeelslid entity)
		{
			this.SendPropertyChanging();
			entity.AdminRechten = this;
		}
		
		private void detach_Personeelslids(Personeelslid entity)
		{
			this.SendPropertyChanging();
			entity.AdminRechten = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bestelling")]
	public partial class Bestelling : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BestellingID;
		
		private System.DateTime _DatumOpgemaakt;
		
		private int _PersoneelslidID;
		
		private System.Nullable<int> _LeverancierID;
		
		private System.Nullable<int> _KlantID;
		
		private System.Nullable<System.DateTime> _DatumVerzending;
		
		private System.Nullable<System.DateTime> _DatumAankomst;
		
		private EntitySet<BestellingProduct> _BestellingProducts;
		
		private EntityRef<Klant> _Klant;
		
		private EntityRef<Leverancier> _Leverancier;
		
		private EntityRef<Personeelslid> _Personeelslid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBestellingIDChanging(int value);
    partial void OnBestellingIDChanged();
    partial void OnDatumOpgemaaktChanging(System.DateTime value);
    partial void OnDatumOpgemaaktChanged();
    partial void OnPersoneelslidIDChanging(int value);
    partial void OnPersoneelslidIDChanged();
    partial void OnLeverancierIDChanging(System.Nullable<int> value);
    partial void OnLeverancierIDChanged();
    partial void OnKlantIDChanging(System.Nullable<int> value);
    partial void OnKlantIDChanged();
    partial void OnDatumVerzendingChanging(System.Nullable<System.DateTime> value);
    partial void OnDatumVerzendingChanged();
    partial void OnDatumAankomstChanging(System.Nullable<System.DateTime> value);
    partial void OnDatumAankomstChanged();
    #endregion
		
		public Bestelling()
		{
			this._BestellingProducts = new EntitySet<BestellingProduct>(new Action<BestellingProduct>(this.attach_BestellingProducts), new Action<BestellingProduct>(this.detach_BestellingProducts));
			this._Klant = default(EntityRef<Klant>);
			this._Leverancier = default(EntityRef<Leverancier>);
			this._Personeelslid = default(EntityRef<Personeelslid>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BestellingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BestellingID
		{
			get
			{
				return this._BestellingID;
			}
			set
			{
				if ((this._BestellingID != value))
				{
					this.OnBestellingIDChanging(value);
					this.SendPropertyChanging();
					this._BestellingID = value;
					this.SendPropertyChanged("BestellingID");
					this.OnBestellingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumOpgemaakt", DbType="DateTime NOT NULL")]
		public System.DateTime DatumOpgemaakt
		{
			get
			{
				return this._DatumOpgemaakt;
			}
			set
			{
				if ((this._DatumOpgemaakt != value))
				{
					this.OnDatumOpgemaaktChanging(value);
					this.SendPropertyChanging();
					this._DatumOpgemaakt = value;
					this.SendPropertyChanged("DatumOpgemaakt");
					this.OnDatumOpgemaaktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersoneelslidID", DbType="Int NOT NULL")]
		public int PersoneelslidID
		{
			get
			{
				return this._PersoneelslidID;
			}
			set
			{
				if ((this._PersoneelslidID != value))
				{
					if (this._Personeelslid.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPersoneelslidIDChanging(value);
					this.SendPropertyChanging();
					this._PersoneelslidID = value;
					this.SendPropertyChanged("PersoneelslidID");
					this.OnPersoneelslidIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeverancierID", DbType="Int")]
		public System.Nullable<int> LeverancierID
		{
			get
			{
				return this._LeverancierID;
			}
			set
			{
				if ((this._LeverancierID != value))
				{
					if (this._Leverancier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLeverancierIDChanging(value);
					this.SendPropertyChanging();
					this._LeverancierID = value;
					this.SendPropertyChanged("LeverancierID");
					this.OnLeverancierIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlantID", DbType="Int")]
		public System.Nullable<int> KlantID
		{
			get
			{
				return this._KlantID;
			}
			set
			{
				if ((this._KlantID != value))
				{
					if (this._Klant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKlantIDChanging(value);
					this.SendPropertyChanging();
					this._KlantID = value;
					this.SendPropertyChanged("KlantID");
					this.OnKlantIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumVerzending", DbType="DateTime")]
		public System.Nullable<System.DateTime> DatumVerzending
		{
			get
			{
				return this._DatumVerzending;
			}
			set
			{
				if ((this._DatumVerzending != value))
				{
					this.OnDatumVerzendingChanging(value);
					this.SendPropertyChanging();
					this._DatumVerzending = value;
					this.SendPropertyChanged("DatumVerzending");
					this.OnDatumVerzendingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumAankomst", DbType="DateTime")]
		public System.Nullable<System.DateTime> DatumAankomst
		{
			get
			{
				return this._DatumAankomst;
			}
			set
			{
				if ((this._DatumAankomst != value))
				{
					this.OnDatumAankomstChanging(value);
					this.SendPropertyChanging();
					this._DatumAankomst = value;
					this.SendPropertyChanged("DatumAankomst");
					this.OnDatumAankomstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bestelling_BestellingProduct", Storage="_BestellingProducts", ThisKey="BestellingID", OtherKey="BestellingID")]
		public EntitySet<BestellingProduct> BestellingProducts
		{
			get
			{
				return this._BestellingProducts;
			}
			set
			{
				this._BestellingProducts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klant_Bestelling", Storage="_Klant", ThisKey="KlantID", OtherKey="KlantID", IsForeignKey=true)]
		public Klant Klant
		{
			get
			{
				return this._Klant.Entity;
			}
			set
			{
				Klant previousValue = this._Klant.Entity;
				if (((previousValue != value) 
							|| (this._Klant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Klant.Entity = null;
						previousValue.Bestellings.Remove(this);
					}
					this._Klant.Entity = value;
					if ((value != null))
					{
						value.Bestellings.Add(this);
						this._KlantID = value.KlantID;
					}
					else
					{
						this._KlantID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Klant");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Leverancier_Bestelling", Storage="_Leverancier", ThisKey="LeverancierID", OtherKey="LeverancierID", IsForeignKey=true)]
		public Leverancier Leverancier
		{
			get
			{
				return this._Leverancier.Entity;
			}
			set
			{
				Leverancier previousValue = this._Leverancier.Entity;
				if (((previousValue != value) 
							|| (this._Leverancier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Leverancier.Entity = null;
						previousValue.Bestellings.Remove(this);
					}
					this._Leverancier.Entity = value;
					if ((value != null))
					{
						value.Bestellings.Add(this);
						this._LeverancierID = value.LeverancierID;
					}
					else
					{
						this._LeverancierID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Leverancier");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personeelslid_Bestelling", Storage="_Personeelslid", ThisKey="PersoneelslidID", OtherKey="PersoneelslidID", IsForeignKey=true)]
		public Personeelslid Personeelslid
		{
			get
			{
				return this._Personeelslid.Entity;
			}
			set
			{
				Personeelslid previousValue = this._Personeelslid.Entity;
				if (((previousValue != value) 
							|| (this._Personeelslid.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Personeelslid.Entity = null;
						previousValue.Bestellings.Remove(this);
					}
					this._Personeelslid.Entity = value;
					if ((value != null))
					{
						value.Bestellings.Add(this);
						this._PersoneelslidID = value.PersoneelslidID;
					}
					else
					{
						this._PersoneelslidID = default(int);
					}
					this.SendPropertyChanged("Personeelslid");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BestellingProducts(BestellingProduct entity)
		{
			this.SendPropertyChanging();
			entity.Bestelling = this;
		}
		
		private void detach_BestellingProducts(BestellingProduct entity)
		{
			this.SendPropertyChanging();
			entity.Bestelling = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BestellingProduct")]
	public partial class BestellingProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BestellingProductID;
		
		private int _BestellingID;
		
		private int _ProductID;
		
		private int _AantalProtuctBesteld;
		
		private EntityRef<Bestelling> _Bestelling;
		
		private EntityRef<Product> _Product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBestellingProductIDChanging(int value);
    partial void OnBestellingProductIDChanged();
    partial void OnBestellingIDChanging(int value);
    partial void OnBestellingIDChanged();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnAantalProtuctBesteldChanging(int value);
    partial void OnAantalProtuctBesteldChanged();
    #endregion
		
		public BestellingProduct()
		{
			this._Bestelling = default(EntityRef<Bestelling>);
			this._Product = default(EntityRef<Product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BestellingProductID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BestellingProductID
		{
			get
			{
				return this._BestellingProductID;
			}
			set
			{
				if ((this._BestellingProductID != value))
				{
					this.OnBestellingProductIDChanging(value);
					this.SendPropertyChanging();
					this._BestellingProductID = value;
					this.SendPropertyChanged("BestellingProductID");
					this.OnBestellingProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BestellingID", DbType="Int NOT NULL")]
		public int BestellingID
		{
			get
			{
				return this._BestellingID;
			}
			set
			{
				if ((this._BestellingID != value))
				{
					if (this._Bestelling.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBestellingIDChanging(value);
					this.SendPropertyChanging();
					this._BestellingID = value;
					this.SendPropertyChanged("BestellingID");
					this.OnBestellingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					if (this._Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AantalProtuctBesteld", DbType="Int NOT NULL")]
		public int AantalProtuctBesteld
		{
			get
			{
				return this._AantalProtuctBesteld;
			}
			set
			{
				if ((this._AantalProtuctBesteld != value))
				{
					this.OnAantalProtuctBesteldChanging(value);
					this.SendPropertyChanging();
					this._AantalProtuctBesteld = value;
					this.SendPropertyChanged("AantalProtuctBesteld");
					this.OnAantalProtuctBesteldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bestelling_BestellingProduct", Storage="_Bestelling", ThisKey="BestellingID", OtherKey="BestellingID", IsForeignKey=true)]
		public Bestelling Bestelling
		{
			get
			{
				return this._Bestelling.Entity;
			}
			set
			{
				Bestelling previousValue = this._Bestelling.Entity;
				if (((previousValue != value) 
							|| (this._Bestelling.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Bestelling.Entity = null;
						previousValue.BestellingProducts.Remove(this);
					}
					this._Bestelling.Entity = value;
					if ((value != null))
					{
						value.BestellingProducts.Add(this);
						this._BestellingID = value.BestellingID;
					}
					else
					{
						this._BestellingID = default(int);
					}
					this.SendPropertyChanged("Bestelling");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_BestellingProduct", Storage="_Product", ThisKey="ProductID", OtherKey="ProductID", IsForeignKey=true)]
		public Product Product
		{
			get
			{
				return this._Product.Entity;
			}
			set
			{
				Product previousValue = this._Product.Entity;
				if (((previousValue != value) 
							|| (this._Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product.Entity = null;
						previousValue.BestellingProducts.Remove(this);
					}
					this._Product.Entity = value;
					if ((value != null))
					{
						value.BestellingProducts.Add(this);
						this._ProductID = value.ProductID;
					}
					else
					{
						this._ProductID = default(int);
					}
					this.SendPropertyChanged("Product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorie")]
	public partial class Categorie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategorieID;
		
		private string _CategorieNaam;
		
		private EntitySet<Product> _Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategorieIDChanging(int value);
    partial void OnCategorieIDChanged();
    partial void OnCategorieNaamChanging(string value);
    partial void OnCategorieNaamChanged();
    #endregion
		
		public Categorie()
		{
			this._Products = new EntitySet<Product>(new Action<Product>(this.attach_Products), new Action<Product>(this.detach_Products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategorieID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategorieID
		{
			get
			{
				return this._CategorieID;
			}
			set
			{
				if ((this._CategorieID != value))
				{
					this.OnCategorieIDChanging(value);
					this.SendPropertyChanging();
					this._CategorieID = value;
					this.SendPropertyChanged("CategorieID");
					this.OnCategorieIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategorieNaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CategorieNaam
		{
			get
			{
				return this._CategorieNaam;
			}
			set
			{
				if ((this._CategorieNaam != value))
				{
					this.OnCategorieNaamChanging(value);
					this.SendPropertyChanging();
					this._CategorieNaam = value;
					this.SendPropertyChanged("CategorieNaam");
					this.OnCategorieNaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorie_Product", Storage="_Products", ThisKey="CategorieID", OtherKey="CategorieID")]
		public EntitySet<Product> Products
		{
			get
			{
				return this._Products;
			}
			set
			{
				this._Products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Categorie = this;
		}
		
		private void detach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Categorie = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klant")]
	public partial class Klant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KlantID;
		
		private string _Voornaam;
		
		private string _Achternaam;
		
		private string _Straatnaam;
		
		private int _Huisnummer;
		
		private string _Bus;
		
		private string _Postcode;
		
		private string _Gemeente;
		
		private string _Telefoonnummer;
		
		private string _Emailadres;
		
		private System.DateTime _AangemaaktOp;
		
		private string _Opmerking;
		
		private EntitySet<Bestelling> _Bestellings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKlantIDChanging(int value);
    partial void OnKlantIDChanged();
    partial void OnVoornaamChanging(string value);
    partial void OnVoornaamChanged();
    partial void OnAchternaamChanging(string value);
    partial void OnAchternaamChanged();
    partial void OnStraatnaamChanging(string value);
    partial void OnStraatnaamChanged();
    partial void OnHuisnummerChanging(int value);
    partial void OnHuisnummerChanged();
    partial void OnBusChanging(string value);
    partial void OnBusChanged();
    partial void OnPostcodeChanging(string value);
    partial void OnPostcodeChanged();
    partial void OnGemeenteChanging(string value);
    partial void OnGemeenteChanged();
    partial void OnTelefoonnummerChanging(string value);
    partial void OnTelefoonnummerChanged();
    partial void OnEmailadresChanging(string value);
    partial void OnEmailadresChanged();
    partial void OnAangemaaktOpChanging(System.DateTime value);
    partial void OnAangemaaktOpChanged();
    partial void OnOpmerkingChanging(string value);
    partial void OnOpmerkingChanged();
    #endregion
		
		public Klant()
		{
			this._Bestellings = new EntitySet<Bestelling>(new Action<Bestelling>(this.attach_Bestellings), new Action<Bestelling>(this.detach_Bestellings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlantID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KlantID
		{
			get
			{
				return this._KlantID;
			}
			set
			{
				if ((this._KlantID != value))
				{
					this.OnKlantIDChanging(value);
					this.SendPropertyChanging();
					this._KlantID = value;
					this.SendPropertyChanged("KlantID");
					this.OnKlantIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voornaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Voornaam
		{
			get
			{
				return this._Voornaam;
			}
			set
			{
				if ((this._Voornaam != value))
				{
					this.OnVoornaamChanging(value);
					this.SendPropertyChanging();
					this._Voornaam = value;
					this.SendPropertyChanged("Voornaam");
					this.OnVoornaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Achternaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Achternaam
		{
			get
			{
				return this._Achternaam;
			}
			set
			{
				if ((this._Achternaam != value))
				{
					this.OnAchternaamChanging(value);
					this.SendPropertyChanging();
					this._Achternaam = value;
					this.SendPropertyChanged("Achternaam");
					this.OnAchternaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Straatnaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Straatnaam
		{
			get
			{
				return this._Straatnaam;
			}
			set
			{
				if ((this._Straatnaam != value))
				{
					this.OnStraatnaamChanging(value);
					this.SendPropertyChanging();
					this._Straatnaam = value;
					this.SendPropertyChanged("Straatnaam");
					this.OnStraatnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Huisnummer", DbType="Int NOT NULL")]
		public int Huisnummer
		{
			get
			{
				return this._Huisnummer;
			}
			set
			{
				if ((this._Huisnummer != value))
				{
					this.OnHuisnummerChanging(value);
					this.SendPropertyChanging();
					this._Huisnummer = value;
					this.SendPropertyChanged("Huisnummer");
					this.OnHuisnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bus", DbType="NVarChar(10)")]
		public string Bus
		{
			get
			{
				return this._Bus;
			}
			set
			{
				if ((this._Bus != value))
				{
					this.OnBusChanging(value);
					this.SendPropertyChanging();
					this._Bus = value;
					this.SendPropertyChanged("Bus");
					this.OnBusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gemeente", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Gemeente
		{
			get
			{
				return this._Gemeente;
			}
			set
			{
				if ((this._Gemeente != value))
				{
					this.OnGemeenteChanging(value);
					this.SendPropertyChanging();
					this._Gemeente = value;
					this.SendPropertyChanged("Gemeente");
					this.OnGemeenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefoonnummer", DbType="NVarChar(24) NOT NULL", CanBeNull=false)]
		public string Telefoonnummer
		{
			get
			{
				return this._Telefoonnummer;
			}
			set
			{
				if ((this._Telefoonnummer != value))
				{
					this.OnTelefoonnummerChanging(value);
					this.SendPropertyChanging();
					this._Telefoonnummer = value;
					this.SendPropertyChanged("Telefoonnummer");
					this.OnTelefoonnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emailadres", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Emailadres
		{
			get
			{
				return this._Emailadres;
			}
			set
			{
				if ((this._Emailadres != value))
				{
					this.OnEmailadresChanging(value);
					this.SendPropertyChanging();
					this._Emailadres = value;
					this.SendPropertyChanged("Emailadres");
					this.OnEmailadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AangemaaktOp", DbType="DateTime NOT NULL")]
		public System.DateTime AangemaaktOp
		{
			get
			{
				return this._AangemaaktOp;
			}
			set
			{
				if ((this._AangemaaktOp != value))
				{
					this.OnAangemaaktOpChanging(value);
					this.SendPropertyChanging();
					this._AangemaaktOp = value;
					this.SendPropertyChanged("AangemaaktOp");
					this.OnAangemaaktOpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opmerking", DbType="NVarChar(MAX)")]
		public string Opmerking
		{
			get
			{
				return this._Opmerking;
			}
			set
			{
				if ((this._Opmerking != value))
				{
					this.OnOpmerkingChanging(value);
					this.SendPropertyChanging();
					this._Opmerking = value;
					this.SendPropertyChanged("Opmerking");
					this.OnOpmerkingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klant_Bestelling", Storage="_Bestellings", ThisKey="KlantID", OtherKey="KlantID")]
		public EntitySet<Bestelling> Bestellings
		{
			get
			{
				return this._Bestellings;
			}
			set
			{
				this._Bestellings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bestellings(Bestelling entity)
		{
			this.SendPropertyChanging();
			entity.Klant = this;
		}
		
		private void detach_Bestellings(Bestelling entity)
		{
			this.SendPropertyChanging();
			entity.Klant = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Leverancier")]
	public partial class Leverancier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LeverancierID;
		
		private string _Contactpersoon;
		
		private string _Telefoonnummer;
		
		private string _Emailadres;
		
		private string _Straatnaam;
		
		private int _Huisnummer;
		
		private string _Bus;
		
		private string _Postcode;
		
		private string _Gemeente;
		
		private EntitySet<Bestelling> _Bestellings;
		
		private EntitySet<Product> _Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLeverancierIDChanging(int value);
    partial void OnLeverancierIDChanged();
    partial void OnContactpersoonChanging(string value);
    partial void OnContactpersoonChanged();
    partial void OnTelefoonnummerChanging(string value);
    partial void OnTelefoonnummerChanged();
    partial void OnEmailadresChanging(string value);
    partial void OnEmailadresChanged();
    partial void OnStraatnaamChanging(string value);
    partial void OnStraatnaamChanged();
    partial void OnHuisnummerChanging(int value);
    partial void OnHuisnummerChanged();
    partial void OnBusChanging(string value);
    partial void OnBusChanged();
    partial void OnPostcodeChanging(string value);
    partial void OnPostcodeChanged();
    partial void OnGemeenteChanging(string value);
    partial void OnGemeenteChanged();
    #endregion
		
		public Leverancier()
		{
			this._Bestellings = new EntitySet<Bestelling>(new Action<Bestelling>(this.attach_Bestellings), new Action<Bestelling>(this.detach_Bestellings));
			this._Products = new EntitySet<Product>(new Action<Product>(this.attach_Products), new Action<Product>(this.detach_Products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeverancierID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LeverancierID
		{
			get
			{
				return this._LeverancierID;
			}
			set
			{
				if ((this._LeverancierID != value))
				{
					this.OnLeverancierIDChanging(value);
					this.SendPropertyChanging();
					this._LeverancierID = value;
					this.SendPropertyChanged("LeverancierID");
					this.OnLeverancierIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contactpersoon", DbType="NVarChar(MAX)")]
		public string Contactpersoon
		{
			get
			{
				return this._Contactpersoon;
			}
			set
			{
				if ((this._Contactpersoon != value))
				{
					this.OnContactpersoonChanging(value);
					this.SendPropertyChanging();
					this._Contactpersoon = value;
					this.SendPropertyChanged("Contactpersoon");
					this.OnContactpersoonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefoonnummer", DbType="NVarChar(24) NOT NULL", CanBeNull=false)]
		public string Telefoonnummer
		{
			get
			{
				return this._Telefoonnummer;
			}
			set
			{
				if ((this._Telefoonnummer != value))
				{
					this.OnTelefoonnummerChanging(value);
					this.SendPropertyChanging();
					this._Telefoonnummer = value;
					this.SendPropertyChanged("Telefoonnummer");
					this.OnTelefoonnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emailadres", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Emailadres
		{
			get
			{
				return this._Emailadres;
			}
			set
			{
				if ((this._Emailadres != value))
				{
					this.OnEmailadresChanging(value);
					this.SendPropertyChanging();
					this._Emailadres = value;
					this.SendPropertyChanged("Emailadres");
					this.OnEmailadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Straatnaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Straatnaam
		{
			get
			{
				return this._Straatnaam;
			}
			set
			{
				if ((this._Straatnaam != value))
				{
					this.OnStraatnaamChanging(value);
					this.SendPropertyChanging();
					this._Straatnaam = value;
					this.SendPropertyChanged("Straatnaam");
					this.OnStraatnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Huisnummer", DbType="Int NOT NULL")]
		public int Huisnummer
		{
			get
			{
				return this._Huisnummer;
			}
			set
			{
				if ((this._Huisnummer != value))
				{
					this.OnHuisnummerChanging(value);
					this.SendPropertyChanging();
					this._Huisnummer = value;
					this.SendPropertyChanged("Huisnummer");
					this.OnHuisnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bus", DbType="NVarChar(10)")]
		public string Bus
		{
			get
			{
				return this._Bus;
			}
			set
			{
				if ((this._Bus != value))
				{
					this.OnBusChanging(value);
					this.SendPropertyChanging();
					this._Bus = value;
					this.SendPropertyChanged("Bus");
					this.OnBusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gemeente", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Gemeente
		{
			get
			{
				return this._Gemeente;
			}
			set
			{
				if ((this._Gemeente != value))
				{
					this.OnGemeenteChanging(value);
					this.SendPropertyChanging();
					this._Gemeente = value;
					this.SendPropertyChanged("Gemeente");
					this.OnGemeenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Leverancier_Bestelling", Storage="_Bestellings", ThisKey="LeverancierID", OtherKey="LeverancierID")]
		public EntitySet<Bestelling> Bestellings
		{
			get
			{
				return this._Bestellings;
			}
			set
			{
				this._Bestellings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Leverancier_Product", Storage="_Products", ThisKey="LeverancierID", OtherKey="LeverancierID")]
		public EntitySet<Product> Products
		{
			get
			{
				return this._Products;
			}
			set
			{
				this._Products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bestellings(Bestelling entity)
		{
			this.SendPropertyChanging();
			entity.Leverancier = this;
		}
		
		private void detach_Bestellings(Bestelling entity)
		{
			this.SendPropertyChanging();
			entity.Leverancier = null;
		}
		
		private void attach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Leverancier = this;
		}
		
		private void detach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Leverancier = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personeelslid")]
	public partial class Personeelslid : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PersoneelslidID;
		
		private string _Voornaam;
		
		private string _Achternaam;
		
		private string _Wachtwoord;
		
		private int _AdminRechtenID;
		
		private string _Salt;
		
		private string _Username;
		
		private System.DateTime _Indiensttreding;
		
		private System.DateTime _GeboorteDatum;
		
		private EntitySet<Bestelling> _Bestellings;
		
		private EntityRef<AdminRechten> _AdminRechten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersoneelslidIDChanging(int value);
    partial void OnPersoneelslidIDChanged();
    partial void OnVoornaamChanging(string value);
    partial void OnVoornaamChanged();
    partial void OnAchternaamChanging(string value);
    partial void OnAchternaamChanged();
    partial void OnWachtwoordChanging(string value);
    partial void OnWachtwoordChanged();
    partial void OnAdminRechtenIDChanging(int value);
    partial void OnAdminRechtenIDChanged();
    partial void OnSaltChanging(string value);
    partial void OnSaltChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnIndiensttredingChanging(System.DateTime value);
    partial void OnIndiensttredingChanged();
    partial void OnGeboorteDatumChanging(System.DateTime value);
    partial void OnGeboorteDatumChanged();
    #endregion
		
		public Personeelslid()
		{
			this._Bestellings = new EntitySet<Bestelling>(new Action<Bestelling>(this.attach_Bestellings), new Action<Bestelling>(this.detach_Bestellings));
			this._AdminRechten = default(EntityRef<AdminRechten>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersoneelslidID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PersoneelslidID
		{
			get
			{
				return this._PersoneelslidID;
			}
			set
			{
				if ((this._PersoneelslidID != value))
				{
					this.OnPersoneelslidIDChanging(value);
					this.SendPropertyChanging();
					this._PersoneelslidID = value;
					this.SendPropertyChanged("PersoneelslidID");
					this.OnPersoneelslidIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voornaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Voornaam
		{
			get
			{
				return this._Voornaam;
			}
			set
			{
				if ((this._Voornaam != value))
				{
					this.OnVoornaamChanging(value);
					this.SendPropertyChanging();
					this._Voornaam = value;
					this.SendPropertyChanged("Voornaam");
					this.OnVoornaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Achternaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Achternaam
		{
			get
			{
				return this._Achternaam;
			}
			set
			{
				if ((this._Achternaam != value))
				{
					this.OnAchternaamChanging(value);
					this.SendPropertyChanging();
					this._Achternaam = value;
					this.SendPropertyChanged("Achternaam");
					this.OnAchternaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wachtwoord", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Wachtwoord
		{
			get
			{
				return this._Wachtwoord;
			}
			set
			{
				if ((this._Wachtwoord != value))
				{
					this.OnWachtwoordChanging(value);
					this.SendPropertyChanging();
					this._Wachtwoord = value;
					this.SendPropertyChanged("Wachtwoord");
					this.OnWachtwoordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminRechtenID", DbType="Int NOT NULL")]
		public int AdminRechtenID
		{
			get
			{
				return this._AdminRechtenID;
			}
			set
			{
				if ((this._AdminRechtenID != value))
				{
					if (this._AdminRechten.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdminRechtenIDChanging(value);
					this.SendPropertyChanging();
					this._AdminRechtenID = value;
					this.SendPropertyChanged("AdminRechtenID");
					this.OnAdminRechtenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salt", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Salt
		{
			get
			{
				return this._Salt;
			}
			set
			{
				if ((this._Salt != value))
				{
					this.OnSaltChanging(value);
					this.SendPropertyChanging();
					this._Salt = value;
					this.SendPropertyChanged("Salt");
					this.OnSaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indiensttreding", DbType="DateTime NOT NULL")]
		public System.DateTime Indiensttreding
		{
			get
			{
				return this._Indiensttreding;
			}
			set
			{
				if ((this._Indiensttreding != value))
				{
					this.OnIndiensttredingChanging(value);
					this.SendPropertyChanging();
					this._Indiensttreding = value;
					this.SendPropertyChanged("Indiensttreding");
					this.OnIndiensttredingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeboorteDatum", DbType="DateTime NOT NULL")]
		public System.DateTime GeboorteDatum
		{
			get
			{
				return this._GeboorteDatum;
			}
			set
			{
				if ((this._GeboorteDatum != value))
				{
					this.OnGeboorteDatumChanging(value);
					this.SendPropertyChanging();
					this._GeboorteDatum = value;
					this.SendPropertyChanged("GeboorteDatum");
					this.OnGeboorteDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personeelslid_Bestelling", Storage="_Bestellings", ThisKey="PersoneelslidID", OtherKey="PersoneelslidID")]
		public EntitySet<Bestelling> Bestellings
		{
			get
			{
				return this._Bestellings;
			}
			set
			{
				this._Bestellings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AdminRechten_Personeelslid", Storage="_AdminRechten", ThisKey="AdminRechtenID", OtherKey="AdminRechtenID", IsForeignKey=true)]
		public AdminRechten AdminRechten
		{
			get
			{
				return this._AdminRechten.Entity;
			}
			set
			{
				AdminRechten previousValue = this._AdminRechten.Entity;
				if (((previousValue != value) 
							|| (this._AdminRechten.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AdminRechten.Entity = null;
						previousValue.Personeelslids.Remove(this);
					}
					this._AdminRechten.Entity = value;
					if ((value != null))
					{
						value.Personeelslids.Add(this);
						this._AdminRechtenID = value.AdminRechtenID;
					}
					else
					{
						this._AdminRechtenID = default(int);
					}
					this.SendPropertyChanged("AdminRechten");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bestellings(Bestelling entity)
		{
			this.SendPropertyChanging();
			entity.Personeelslid = this;
		}
		
		private void detach_Bestellings(Bestelling entity)
		{
			this.SendPropertyChanging();
			entity.Personeelslid = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductID;
		
		private string _Naam;
		
		private decimal _Marge;
		
		private string _Eenheid;
		
		private decimal _BTW;
		
		private int _LeverancierID;
		
		private int _CategorieID;
		
		private int _AantalOpVooraad;
		
		private System.Nullable<int> _AantalNaBesteld;
		
		private System.Nullable<int> _AantalBesteld;
		
		private System.Nullable<int> _AantalBeschikbaar;
		
		private decimal _AankoopPrijs;
		
		private EntitySet<BestellingProduct> _BestellingProducts;
		
		private EntityRef<Categorie> _Categorie;
		
		private EntityRef<Leverancier> _Leverancier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnNaamChanging(string value);
    partial void OnNaamChanged();
    partial void OnMargeChanging(decimal value);
    partial void OnMargeChanged();
    partial void OnEenheidChanging(string value);
    partial void OnEenheidChanged();
    partial void OnBTWChanging(decimal value);
    partial void OnBTWChanged();
    partial void OnLeverancierIDChanging(int value);
    partial void OnLeverancierIDChanged();
    partial void OnCategorieIDChanging(int value);
    partial void OnCategorieIDChanged();
    partial void OnAantalOpVooraadChanging(int value);
    partial void OnAantalOpVooraadChanged();
    partial void OnAantalNaBesteldChanging(System.Nullable<int> value);
    partial void OnAantalNaBesteldChanged();
    partial void OnAantalBesteldChanging(System.Nullable<int> value);
    partial void OnAantalBesteldChanged();
    partial void OnAantalBeschikbaarChanging(System.Nullable<int> value);
    partial void OnAantalBeschikbaarChanged();
    partial void OnAankoopPrijsChanging(decimal value);
    partial void OnAankoopPrijsChanged();
    #endregion
		
		public Product()
		{
			this._BestellingProducts = new EntitySet<BestellingProduct>(new Action<BestellingProduct>(this.attach_BestellingProducts), new Action<BestellingProduct>(this.detach_BestellingProducts));
			this._Categorie = default(EntityRef<Categorie>);
			this._Leverancier = default(EntityRef<Leverancier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Naam
		{
			get
			{
				return this._Naam;
			}
			set
			{
				if ((this._Naam != value))
				{
					this.OnNaamChanging(value);
					this.SendPropertyChanging();
					this._Naam = value;
					this.SendPropertyChanged("Naam");
					this.OnNaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marge", DbType="Decimal(8,3) NOT NULL")]
		public decimal Marge
		{
			get
			{
				return this._Marge;
			}
			set
			{
				if ((this._Marge != value))
				{
					this.OnMargeChanging(value);
					this.SendPropertyChanging();
					this._Marge = value;
					this.SendPropertyChanged("Marge");
					this.OnMargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eenheid", DbType="NVarChar(50)")]
		public string Eenheid
		{
			get
			{
				return this._Eenheid;
			}
			set
			{
				if ((this._Eenheid != value))
				{
					this.OnEenheidChanging(value);
					this.SendPropertyChanging();
					this._Eenheid = value;
					this.SendPropertyChanged("Eenheid");
					this.OnEenheidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BTW", DbType="Decimal(5,2) NOT NULL")]
		public decimal BTW
		{
			get
			{
				return this._BTW;
			}
			set
			{
				if ((this._BTW != value))
				{
					this.OnBTWChanging(value);
					this.SendPropertyChanging();
					this._BTW = value;
					this.SendPropertyChanged("BTW");
					this.OnBTWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeverancierID", DbType="Int NOT NULL")]
		public int LeverancierID
		{
			get
			{
				return this._LeverancierID;
			}
			set
			{
				if ((this._LeverancierID != value))
				{
					if (this._Leverancier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLeverancierIDChanging(value);
					this.SendPropertyChanging();
					this._LeverancierID = value;
					this.SendPropertyChanged("LeverancierID");
					this.OnLeverancierIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategorieID", DbType="Int NOT NULL")]
		public int CategorieID
		{
			get
			{
				return this._CategorieID;
			}
			set
			{
				if ((this._CategorieID != value))
				{
					if (this._Categorie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCategorieIDChanging(value);
					this.SendPropertyChanging();
					this._CategorieID = value;
					this.SendPropertyChanged("CategorieID");
					this.OnCategorieIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AantalOpVooraad", DbType="Int NOT NULL")]
		public int AantalOpVooraad
		{
			get
			{
				return this._AantalOpVooraad;
			}
			set
			{
				if ((this._AantalOpVooraad != value))
				{
					this.OnAantalOpVooraadChanging(value);
					this.SendPropertyChanging();
					this._AantalOpVooraad = value;
					this.SendPropertyChanged("AantalOpVooraad");
					this.OnAantalOpVooraadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AantalNaBesteld", DbType="Int")]
		public System.Nullable<int> AantalNaBesteld
		{
			get
			{
				return this._AantalNaBesteld;
			}
			set
			{
				if ((this._AantalNaBesteld != value))
				{
					this.OnAantalNaBesteldChanging(value);
					this.SendPropertyChanging();
					this._AantalNaBesteld = value;
					this.SendPropertyChanged("AantalNaBesteld");
					this.OnAantalNaBesteldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AantalBesteld", DbType="Int")]
		public System.Nullable<int> AantalBesteld
		{
			get
			{
				return this._AantalBesteld;
			}
			set
			{
				if ((this._AantalBesteld != value))
				{
					this.OnAantalBesteldChanging(value);
					this.SendPropertyChanging();
					this._AantalBesteld = value;
					this.SendPropertyChanged("AantalBesteld");
					this.OnAantalBesteldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AantalBeschikbaar", DbType="Int")]
		public System.Nullable<int> AantalBeschikbaar
		{
			get
			{
				return this._AantalBeschikbaar;
			}
			set
			{
				if ((this._AantalBeschikbaar != value))
				{
					this.OnAantalBeschikbaarChanging(value);
					this.SendPropertyChanging();
					this._AantalBeschikbaar = value;
					this.SendPropertyChanged("AantalBeschikbaar");
					this.OnAantalBeschikbaarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AankoopPrijs", DbType="Decimal(8,2) NOT NULL")]
		public decimal AankoopPrijs
		{
			get
			{
				return this._AankoopPrijs;
			}
			set
			{
				if ((this._AankoopPrijs != value))
				{
					this.OnAankoopPrijsChanging(value);
					this.SendPropertyChanging();
					this._AankoopPrijs = value;
					this.SendPropertyChanged("AankoopPrijs");
					this.OnAankoopPrijsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_BestellingProduct", Storage="_BestellingProducts", ThisKey="ProductID", OtherKey="ProductID")]
		public EntitySet<BestellingProduct> BestellingProducts
		{
			get
			{
				return this._BestellingProducts;
			}
			set
			{
				this._BestellingProducts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorie_Product", Storage="_Categorie", ThisKey="CategorieID", OtherKey="CategorieID", IsForeignKey=true)]
		public Categorie Categorie
		{
			get
			{
				return this._Categorie.Entity;
			}
			set
			{
				Categorie previousValue = this._Categorie.Entity;
				if (((previousValue != value) 
							|| (this._Categorie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categorie.Entity = null;
						previousValue.Products.Remove(this);
					}
					this._Categorie.Entity = value;
					if ((value != null))
					{
						value.Products.Add(this);
						this._CategorieID = value.CategorieID;
					}
					else
					{
						this._CategorieID = default(int);
					}
					this.SendPropertyChanged("Categorie");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Leverancier_Product", Storage="_Leverancier", ThisKey="LeverancierID", OtherKey="LeverancierID", IsForeignKey=true)]
		public Leverancier Leverancier
		{
			get
			{
				return this._Leverancier.Entity;
			}
			set
			{
				Leverancier previousValue = this._Leverancier.Entity;
				if (((previousValue != value) 
							|| (this._Leverancier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Leverancier.Entity = null;
						previousValue.Products.Remove(this);
					}
					this._Leverancier.Entity = value;
					if ((value != null))
					{
						value.Products.Add(this);
						this._LeverancierID = value.LeverancierID;
					}
					else
					{
						this._LeverancierID = default(int);
					}
					this.SendPropertyChanged("Leverancier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BestellingProducts(BestellingProduct entity)
		{
			this.SendPropertyChanging();
			entity.Product = this;
		}
		
		private void detach_BestellingProducts(BestellingProduct entity)
		{
			this.SendPropertyChanging();
			entity.Product = null;
		}
	}
}
#pragma warning restore 1591
